### PR TITLE
Issue #50: Added a new scope function to new.controller.js to resolve status bar issue

### PR DESCRIPTION
**Pull request by karencalpo**
Issue #50: Added a new scope function to www/js/controllers/new.controller.js to resolve status bar issue. Please test on iOS device (I do not have a setup to test on an iOS device).

### CODE REVIEW

**Comment by clarle** [comment]
LGTM

**Comment by arichen** [comment]
Status bar still not showing on iOS ..

**Comment by karencalpo** [comment]
I won't have a Mac to work with much longer. Can you assign the defect to someone else?

-Karen

**Comment by arichen** [comment]
Sure!

**Pull request closed without merging**
